// Generated in relicta sound patcher. Version 3.0
class CfgMusic {
class rm_0 { titles[] = {0,""};
	name = "round\common_end1.ogg";
	sound[] = {PATHMUSICCFG(round\common_end1.ogg), db+0, 1.0};
	duration = 73;
};
class rm_1 { titles[] = {0,""};
	name = "round\endround1.ogg";
	sound[] = {PATHMUSICCFG(round\endround1.ogg), db+0, 1.0};
	duration = 74;
};
class rm_2 { titles[] = {0,""};
	name = "round\endround2.ogg";
	sound[] = {PATHMUSICCFG(round\endround2.ogg), db+0, 1.0};
	duration = 50;
};
class rm_3 { titles[] = {0,""};
	name = "round\end_newarmy.ogg";
	sound[] = {PATHMUSICCFG(round\end_newarmy.ogg), db+0, 1.0};
	duration = 45;
};
class rm_4 { titles[] = {0,""};
	name = "round\end_tutu.ogg";
	sound[] = {PATHMUSICCFG(round\end_tutu.ogg), db+0, 1.0};
	duration = 57;
};
class rm_5 { titles[] = {0,""};
	name = "round\kingpin.ogg";
	sound[] = {PATHMUSICCFG(round\kingpin.ogg), db+0, 1.0};
	duration = 22;
};
class rm_6 { titles[] = {0,""};
	name = "round\rashod.ogg";
	sound[] = {PATHMUSICCFG(round\rashod.ogg), db+0, 1.0};
	duration = 133;
};
class rm_7 { titles[] = {0,""};
	name = "round\start_1.ogg";
	sound[] = {PATHMUSICCFG(round\start_1.ogg), db+0, 1.0};
	duration = 10;
};
class rm_8 { titles[] = {0,""};
	name = "round\start_2.ogg";
	sound[] = {PATHMUSICCFG(round\start_2.ogg), db+0, 1.0};
	duration = 13;
};
class rm_9 { titles[] = {0,""};
	name = "round\start_zlachnik.ogg";
	sound[] = {PATHMUSICCFG(round\start_zlachnik.ogg), db+0, 1.0};
	duration = 24;
};
class rm_10 { titles[] = {0,""};
	name = "round\start_zlachnik_bandit.ogg";
	sound[] = {PATHMUSICCFG(round\start_zlachnik_bandit.ogg), db+0, 1.0};
	duration = 18;
};
class rm_11 { titles[] = {0,""};
	name = "mode\Dark_Out.ogg";
	sound[] = {PATHMUSICCFG(mode\Dark_Out.ogg), db+0, 1.0};
	duration = 127;
};
class rm_12 { titles[] = {0,""};
	name = "mode\Miracle_Workshop.ogg";
	sound[] = {PATHMUSICCFG(mode\Miracle_Workshop.ogg), db+0, 1.0};
	duration = 171;
};
class rm_13 { titles[] = {0,""};
	name = "mode\Phlegethon.ogg";
	sound[] = {PATHMUSICCFG(mode\Phlegethon.ogg), db+0, 1.0};
	duration = 183;
};
class rm_14 { titles[] = {0,""};
	name = "lobby\Atrium Carceri - Reselected.ogg";
	sound[] = {PATHMUSICCFG(lobby\Atrium Carceri - Reselected.ogg), db+0, 1.0};
	duration = 275;
};
class rm_15 { titles[] = {0,""};
	name = "lobby\A_Curved_Blade.ogg";
	sound[] = {PATHMUSICCFG(lobby\A_Curved_Blade.ogg), db+0, 1.0};
	duration = 356;
};
class rm_16 { titles[] = {0,""};
	name = "lobby\A_Rope_to_End_It_All.ogg";
	sound[] = {PATHMUSICCFG(lobby\A_Rope_to_End_It_All.ogg), db+0, 1.0};
	duration = 204;
};
class rm_17 { titles[] = {0,""};
	name = "lobby\Conflict.ogg";
	sound[] = {PATHMUSICCFG(lobby\Conflict.ogg), db+0, 1.0};
	duration = 147;
};
class rm_18 { titles[] = {0,""};
	name = "lobby\Dark_Water.ogg";
	sound[] = {PATHMUSICCFG(lobby\Dark_Water.ogg), db+0, 1.0};
	duration = 250;
};
class rm_19 { titles[] = {0,""};
	name = "lobby\Endless_Deep.ogg";
	sound[] = {PATHMUSICCFG(lobby\Endless_Deep.ogg), db+0, 1.0};
	duration = 272;
};
class rm_20 { titles[] = {0,""};
	name = "lobby\End_of_the_Century.ogg";
	sound[] = {PATHMUSICCFG(lobby\End_of_the_Century.ogg), db+0, 1.0};
	duration = 441;
};
class rm_21 { titles[] = {0,""};
	name = "lobby\Faces_of_War.ogg";
	sound[] = {PATHMUSICCFG(lobby\Faces_of_War.ogg), db+0, 1.0};
	duration = 326;
};
class rm_22 { titles[] = {0,""};
	name = "lobby\First_Steps.ogg";
	sound[] = {PATHMUSICCFG(lobby\First_Steps.ogg), db+0, 1.0};
	duration = 243;
};
class rm_23 { titles[] = {0,""};
	name = "lobby\Floor_6_Please.ogg";
	sound[] = {PATHMUSICCFG(lobby\Floor_6_Please.ogg), db+0, 1.0};
	duration = 175;
};
class rm_24 { titles[] = {0,""};
	name = "lobby\Hypnoz.ogg";
	sound[] = {PATHMUSICCFG(lobby\Hypnoz.ogg), db+0, 1.0};
	duration = 232;
};
class rm_25 { titles[] = {0,""};
	name = "lobby\K.Stanislavsky - Now Im Ready.ogg";
	sound[] = {PATHMUSICCFG(lobby\K.Stanislavsky - Now Im Ready.ogg), db+0, 1.0};
	duration = 200;
};
class rm_26 { titles[] = {0,""};
	name = "lobby\Kuroi_Jukai.ogg";
	sound[] = {PATHMUSICCFG(lobby\Kuroi_Jukai.ogg), db+0, 1.0};
	duration = 301;
};
class rm_27 { titles[] = {0,""};
	name = "events\Burial.ogg";
	sound[] = {PATHMUSICCFG(events\Burial.ogg), db+0, 1.0};
	duration = 181;
};
class rm_28 { titles[] = {0,""};
	name = "events\Floating.ogg";
	sound[] = {PATHMUSICCFG(events\Floating.ogg), db+0, 1.0};
	duration = 162;
};
class rm_29 { titles[] = {0,""};
	name = "events\Manufactured_Minds.ogg";
	sound[] = {PATHMUSICCFG(events\Manufactured_Minds.ogg), db+0, 1.0};
	duration = 258;
};
class rm_30 { titles[] = {0,""};
	name = "events\Meltdown.ogg";
	sound[] = {PATHMUSICCFG(events\Meltdown.ogg), db+0, 1.0};
	duration = 174;
};
class rm_31 { titles[] = {0,""};
	name = "events\Shimmering_with_Horn_of_Woe.ogg";
	sound[] = {PATHMUSICCFG(events\Shimmering_with_Horn_of_Woe.ogg), db+0, 1.0};
	duration = 474;
};
class rm_32 { titles[] = {0,""};
	name = "events\Through_the_Loop.ogg";
	sound[] = {PATHMUSICCFG(events\Through_the_Loop.ogg), db+0, 1.0};
	duration = 241;
};
class rm_33 { titles[] = {0,""};
	name = "events\Tranquility.ogg";
	sound[] = {PATHMUSICCFG(events\Tranquility.ogg), db+0, 1.0};
	duration = 180;
};
class rm_34 { titles[] = {0,""};
	name = "events\Warden.ogg";
	sound[] = {PATHMUSICCFG(events\Warden.ogg), db+0, 1.0};
	duration = 157;
};
class rm_35 { titles[] = {0,""};
	name = "dead\Burgundian-Lullaby.ogg";
	sound[] = {PATHMUSICCFG(dead\Burgundian-Lullaby.ogg), db+0, 1.0};
	duration = 212;
};
class rm_36 { titles[] = {0,""};
	name = "caveambient\Deadbeat_II__Remastered.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Deadbeat_II__Remastered.ogg), db+0, 1.0};
	duration = 257;
};
class rm_37 { titles[] = {0,""};
	name = "caveambient\Dreamhours.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Dreamhours.ogg), db+0, 1.0};
	duration = 465;
};
class rm_38 { titles[] = {0,""};
	name = "caveambient\Gods_Shadow_on_Earth__Remastered.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Gods_Shadow_on_Earth__Remastered.ogg), db+0, 1.0};
	duration = 253;
};
class rm_39 { titles[] = {0,""};
	name = "caveambient\Old_Tunnels.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Old_Tunnels.ogg), db+0, 1.0};
	duration = 301;
};
class rm_40 { titles[] = {0,""};
	name = "caveambient\Permafrost.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Permafrost.ogg), db+0, 1.0};
	duration = 392;
};
class rm_41 { titles[] = {0,""};
	name = "caveambient\Sacrum_Noctis.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Sacrum_Noctis.ogg), db+0, 1.0};
	duration = 547;
};
class rm_42 { titles[] = {0,""};
	name = "caveambient\Staring_At_Nothing.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Staring_At_Nothing.ogg), db+0, 1.0};
	duration = 283;
};
class rm_43 { titles[] = {0,""};
	name = "caveambient\Static_of_the_Kapnobatai.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Static_of_the_Kapnobatai.ogg), db+0, 1.0};
	duration = 611;
};
class rm_44 { titles[] = {0,""};
	name = "caveambient\The_Dead_City.ogg";
	sound[] = {PATHMUSICCFG(caveambient\The_Dead_City.ogg), db+0, 1.0};
	duration = 331;
};
class rm_45 { titles[] = {0,""};
	name = "caveambient\Trembling.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Trembling.ogg), db+0, 1.0};
	duration = 253;
};
class rm_46 { titles[] = {0,""};
	name = "caveambient\Victorian_Meltdown.ogg";
	sound[] = {PATHMUSICCFG(caveambient\Victorian_Meltdown.ogg), db+0, 1.0};
	duration = 497;
};
class rm_47 { titles[] = {0,""};
	name = "ambient\All_Things_Nocturnal.ogg";
	sound[] = {PATHMUSICCFG(ambient\All_Things_Nocturnal.ogg), db+0, 1.0};
	duration = 332;
};
class rm_48 { titles[] = {0,""};
	name = "ambient\Anthropic_Uncreation.ogg";
	sound[] = {PATHMUSICCFG(ambient\Anthropic_Uncreation.ogg), db+0, 1.0};
	duration = 316;
};
class rm_49 { titles[] = {0,""};
	name = "ambient\An_Atrementous_City.ogg";
	sound[] = {PATHMUSICCFG(ambient\An_Atrementous_City.ogg), db+0, 1.0};
	duration = 280;
};
class rm_50 { titles[] = {0,""};
	name = "ambient\Asylum.ogg";
	sound[] = {PATHMUSICCFG(ambient\Asylum.ogg), db+0, 1.0};
	duration = 316;
};
class rm_51 { titles[] = {0,""};
	name = "ambient\A_New_Age.ogg";
	sound[] = {PATHMUSICCFG(ambient\A_New_Age.ogg), db+0, 1.0};
	duration = 319;
};
class rm_52 { titles[] = {0,""};
	name = "ambient\Black_Feathers.ogg";
	sound[] = {PATHMUSICCFG(ambient\Black_Feathers.ogg), db+0, 1.0};
	duration = 352;
};
class rm_53 { titles[] = {0,""};
	name = "ambient\Decrepit_City.ogg";
	sound[] = {PATHMUSICCFG(ambient\Decrepit_City.ogg), db+0, 1.0};
	duration = 217;
};
class rm_54 { titles[] = {0,""};
	name = "ambient\Entrance.ogg";
	sound[] = {PATHMUSICCFG(ambient\Entrance.ogg), db+0, 1.0};
	duration = 120;
};
class rm_55 { titles[] = {0,""};
	name = "ambient\Hiding.ogg";
	sound[] = {PATHMUSICCFG(ambient\Hiding.ogg), db+0, 1.0};
	duration = 380;
};
class rm_56 { titles[] = {0,""};
	name = "ambient\House_of_Tinctures.ogg";
	sound[] = {PATHMUSICCFG(ambient\House_of_Tinctures.ogg), db+0, 1.0};
	duration = 283;
};
class rm_57 { titles[] = {0,""};
	name = "ambient\Hypnagoga.ogg";
	sound[] = {PATHMUSICCFG(ambient\Hypnagoga.ogg), db+0, 1.0};
	duration = 248;
};
class rm_58 { titles[] = {0,""};
	name = "ambient\Laudanum.ogg";
	sound[] = {PATHMUSICCFG(ambient\Laudanum.ogg), db+0, 1.0};
	duration = 265;
};
class rm_59 { titles[] = {0,""};
	name = "ambient\Maintenance_Tunnels.ogg";
	sound[] = {PATHMUSICCFG(ambient\Maintenance_Tunnels.ogg), db+0, 1.0};
	duration = 273;
};
class rm_60 { titles[] = {0,""};
	name = "ambient\Memory_Lapse.ogg";
	sound[] = {PATHMUSICCFG(ambient\Memory_Lapse.ogg), db+0, 1.0};
	duration = 210;
};
class rm_61 { titles[] = {0,""};
	name = "ambient\Miles_to_Midnight.ogg";
	sound[] = {PATHMUSICCFG(ambient\Miles_to_Midnight.ogg), db+0, 1.0};
	duration = 350;
};
class rm_62 { titles[] = {0,""};
	name = "ambient\Mind_Turns_to_Night.ogg";
	sound[] = {PATHMUSICCFG(ambient\Mind_Turns_to_Night.ogg), db+0, 1.0};
	duration = 252;
};
class rm_63 { titles[] = {0,""};
	name = "ambient\Monument.ogg";
	sound[] = {PATHMUSICCFG(ambient\Monument.ogg), db+0, 1.0};
	duration = 337;
};
class rm_64 { titles[] = {0,""};
	name = "ambient\Prisoner_of_Night_and_Fog.ogg";
	sound[] = {PATHMUSICCFG(ambient\Prisoner_of_Night_and_Fog.ogg), db+0, 1.0};
	duration = 265;
};
class rm_65 { titles[] = {0,""};
	name = "ambient\Thermographic_Components.ogg";
	sound[] = {PATHMUSICCFG(ambient\Thermographic_Components.ogg), db+0, 1.0};
	duration = 338;
};
class rm_66 { titles[] = {0,""};
	name = "ambient\The_Great_Order_of_Things.ogg";
	sound[] = {PATHMUSICCFG(ambient\The_Great_Order_of_Things.ogg), db+0, 1.0};
	duration = 284;
};
class rm_67 { titles[] = {0,""};
	name = "ambient\Time_Freeze.ogg";
	sound[] = {PATHMUSICCFG(ambient\Time_Freeze.ogg), db+0, 1.0};
	duration = 343;
};
	maxRMIndex = 67;
};