// ======================================================
// Copyright (c) 2017-2023 the ReSDK_A3 project
// sdk.relicta.ru
// ======================================================

#define SLIGHT_MAGICSTORM_DEBUG 2100
#define SLIGHT_SET123_DEBUG 2101
#define SLIGHT_TEMPLATE_DIRECTLIGHT 2102
#define SLIGHT_TEMPLATE_POINTLIGHT 2103
#define SLIGHT_LIGHTKOPILKA 2104
#define SLIGHT_LIGHTCELLKOPILKA 2105
#define SLIGHT_KOPILKAREDLIGHT 2106
#define SLIGHT_LIGHTKOPILKAMEDIUM 2107

#ifdef SCRIPT_EMIT_EVAL_SERVER

	SLIGHT_MAGICSTORM_DEBUG_var = 2100;
	SLIGHT_SET123_DEBUG_var = 2101;
	SLIGHT_TEMPLATE_DIRECTLIGHT_var = 2102;
	SLIGHT_TEMPLATE_POINTLIGHT_var = 2103;
	SLIGHT_LIGHTKOPILKA_var = 2104;
	SLIGHT_LIGHTCELLKOPILKA_var = 2105;
	SLIGHT_KOPILKAREDLIGHT_var = 2106;
	SLIGHT_LIGHTKOPILKAMEDIUM_var = 2107;
#endif