# This is a basic workflow to help you get started with Actions

name: Validate client

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request_target:
    branches: [ "main" ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v3  
      
      - name: Run Validation (merged on main)
        if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
        # if: ${{ github.repository == 'Relicta-Team/ReSDK_A3.vr' && github.ref == 'refs/heads/main' }}
        env: 
          SRCPATH: src|src
        run: Third-party/VirtualMachine/sqfvm.exe --suppress-welcome --nowarn -a --input-sqf ./src/client/vm_compile.sqf -v ${env:SRCPATH} -D __FLAG_ONLY_PARSE__ -D CMD__RELEASE -D __GH_ACTION
        working-directory: ${{ github.workspace }}

